{{- if .Values.prometheusOperator.networkPolicy.enabled }}
apiVersion: {{ template "unitest-stack.prometheus.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ template "unitest-stack.fullname" . }}-operator
  namespace: {{ template "unitest-stack.namespace" . }}
  labels:
    app: {{ template "unitest-stack.name" . }}-operator
spec:
  egress:
    - {}
  ingress:
    - ports:
      {{- if .Values.prometheusOperator.tls.enabled }}
      - port: {{ .Values.prometheusOperator.tls.internalPort }}
      {{- else }}
      - port: 8080
      {{- end }}
  policyTypes:
    - Egress
    - Ingress
  podSelector:
    matchLabels:
      app: {{ template "unitest-stack.name" . }}-operator
      release: {{ $.Release.Name | quote }}
{{- end }}
