{{- if and .Values.prometheusOperator.enabled .Values.global.rbac.create .Values.global.rbac.pspEnabled }}
{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "unitest-stack.fullname" . }}-operator-psp
  labels:
    app: {{ template "unitest-stack.name" . }}-operator
{{ include "unitest-stack.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "unitest-stack.fullname" . }}-operator-psp
subjects:
  - kind: ServiceAccount
    name: {{ template "unitest-stack.operator.serviceAccountName" . }}
    namespace: {{ template "unitest-stack.namespace" . }}
{{- end }}
{{- end }}
