{{- if and (.Capabilities.APIVersions.Has "autoscaling.k8s.io/v1") (.Values.prometheusOperator.verticalPodAutoscaler.enabled) }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "unitest-stack.fullname" . }}-operator
  namespace: {{ template "unitest-stack.namespace" . }}
  labels:
    app: {{ template "unitest-stack.name" . }}-operator
{{ include "unitest-stack.labels" . | indent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: {{ template "unitest-stack.name" . }}
      {{- if .Values.prometheusOperator.verticalPodAutoscaler.controlledResources }}
      controlledResources: {{ .Values.prometheusOperator.verticalPodAutoscaler.controlledResources }}
      {{- end }}
      {{- if .Values.prometheusOperator.verticalPodAutoscaler.maxAllowed }}
      maxAllowed:
        {{ toYaml .Values.prometheusOperator.verticalPodAutoscaler.maxAllowed | nindent 8 }}
      {{- end }}
      {{- if .Values.prometheusOperator.verticalPodAutoscaler.minAllowed }}
      minAllowed:
        {{ toYaml .Values.prometheusOperator.verticalPodAutoscaler.minAllowed | nindent 8 }}
      {{- end }}
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{ template "unitest-stack.fullname" . }}
  {{- if .Values.prometheusOperator.verticalPodAutoscaler.updatePolicy }}
  updatePolicy:
    {{- if .Values.prometheusOperator.verticalPodAutoscaler.updatePolicy.updateMode }}
    updateMode: {{ .Values.prometheusOperator.verticalPodAutoscaler.updatePolicy.updateMode  }}
    {{- end }}
  {{- end }}
{{- end }}
