{{- if and .Values.prometheus.enabled .Values.prometheus.podDisruptionBudget.enabled }}
apiVersion: {{ include "unitest-stack.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "unitest-stack.fullname" . }}-prometheus
  namespace: {{ template "unitest-stack.namespace" . }}
  labels:
    app: {{ template "unitest-stack.name" . }}-prometheus
{{ include "unitest-stack.labels" . | indent 4 }}
spec:
  {{- if .Values.prometheus.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.prometheus.podDisruptionBudget.minAvailable }}
  {{- end  }}
  {{- if .Values.prometheus.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.prometheus.podDisruptionBudget.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      prometheus: {{ template "unitest-stack.prometheus.crname" . }}
{{- end }}
