{{- if and .Values.prometheus.enabled .Values.global.rbac.create .Values.global.rbac.pspEnabled }}
{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "unitest-stack.fullname" . }}-prometheus-psp
  labels:
    app: {{ template "unitest-stack.name" . }}-prometheus
{{ include "unitest-stack.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "unitest-stack.fullname" . }}-prometheus-psp
subjects:
  - kind: ServiceAccount
    name: {{ template "unitest-stack.prometheus.serviceAccountName" . }}
    namespace: {{ template "unitest-stack.namespace" . }}
{{- end }}
{{- end }}
