{{- if and .Values.prometheus.enabled .Values.prometheus.additionalServiceMonitors }}
apiVersion: v1
kind: List
items:
{{- range .Values.prometheus.additionalServiceMonitors }}
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: {{ .name }}
      namespace: {{ template "unitest-stack.namespace" $ }}
      labels:
        app: {{ template "unitest-stack.name" $ }}-prometheus
{{ include "unitest-stack.labels" $ | indent 8 }}
        {{- if .additionalLabels }}
{{ toYaml .additionalLabels | indent 8 }}
        {{- end }}
    spec:
      endpoints:
{{ toYaml .endpoints | indent 8 }}
    {{- if .jobLabel }}
      jobLabel: {{ .jobLabel }}
    {{- end }}
    {{- if .namespaceSelector }}
      namespaceSelector:
{{ toYaml .namespaceSelector | indent 8 }}
    {{- end }}
      selector:
{{ toYaml .selector | indent 8 }}
    {{- if .targetLabels }}
      targetLabels:
{{ toYaml .targetLabels | indent 8 }}
    {{- end }}
    {{- if .podTargetLabels }}
      podTargetLabels:
{{ toYaml .podTargetLabels | indent 8 }}
    {{- end }}
{{- end }}
{{- end }}
